"""empty message

Revision ID: 0abcde47ab0f
Revises: 41826fb52d1a
Create Date: 2019-09-05 14:16:31.608117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0abcde47ab0f'
down_revision = '41826fb52d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('first_names', sa.Column('telegram_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'first_names', 'telegram_users', ['telegram_user_id'], ['id'])
    op.add_column('last_names', sa.Column('telegram_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'last_names', 'telegram_users', ['telegram_user_id'], ['id'])
    op.drop_constraint('phone_numbers_telegram_user_id_fkey', 'phone_numbers', type_='foreignkey')
    op.create_foreign_key(None, 'phone_numbers', 'telegram_users', ['telegram_user_id'], ['id'])
    op.drop_constraint('user_names_telegram_user_id_fkey', 'user_names', type_='foreignkey')
    op.create_foreign_key(None, 'user_names', 'telegram_users', ['telegram_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_names', type_='foreignkey')
    op.create_foreign_key('user_names_telegram_user_id_fkey', 'user_names', 'user_names', ['telegram_user_id'], ['id'])
    op.drop_constraint(None, 'phone_numbers', type_='foreignkey')
    op.create_foreign_key('phone_numbers_telegram_user_id_fkey', 'phone_numbers', 'phone_numbers', ['telegram_user_id'], ['id'])
    op.drop_constraint(None, 'last_names', type_='foreignkey')
    op.drop_column('last_names', 'telegram_user_id')
    op.drop_constraint(None, 'first_names', type_='foreignkey')
    op.drop_column('first_names', 'telegram_user_id')
    # ### end Alembic commands ###
