"""empty message

Revision ID: 41826fb52d1a
Revises: 559a6bf48c08
Create Date: 2019-09-04 23:57:43.860449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41826fb52d1a'
down_revision = '559a6bf48c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('telegram_users_last_name_id_fkey', 'telegram_users', type_='foreignkey')
    op.drop_constraint('telegram_users_first_name_id_fkey', 'telegram_users', type_='foreignkey')
    op.drop_column('telegram_users', 'first_name_id')
    op.drop_column('telegram_users', 'last_name_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('last_name_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('telegram_users', sa.Column('first_name_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('telegram_users_first_name_id_fkey', 'telegram_users', 'last_names', ['first_name_id'], ['id'])
    op.create_foreign_key('telegram_users_last_name_id_fkey', 'telegram_users', 'last_names', ['last_name_id'], ['id'])
    # ### end Alembic commands ###
