"""empty message

Revision ID: 559a6bf48c08
Revises: e1e43fda8a79
Create Date: 2019-09-04 23:57:07.032584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559a6bf48c08'
down_revision = 'e1e43fda8a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('first_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_name')
    )
    op.create_table('last_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('last_name')
    )
    op.add_column('phone_numbers', sa.Column('telegram_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'phone_numbers', 'phone_numbers', ['telegram_user_id'], ['id'])
    op.add_column('telegram_users', sa.Column('first_name_id', sa.Integer(), nullable=True))
    op.add_column('telegram_users', sa.Column('last_name_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'telegram_users', ['id'])
    op.drop_constraint('telegram_users_user_name_id_fkey', 'telegram_users', type_='foreignkey')
    op.drop_constraint('telegram_users_phone_number_id_fkey', 'telegram_users', type_='foreignkey')
    op.create_foreign_key(None, 'telegram_users', 'last_names', ['first_name_id'], ['id'])
    op.create_foreign_key(None, 'telegram_users', 'last_names', ['last_name_id'], ['id'])
    op.drop_column('telegram_users', 'is_self')
    op.drop_column('telegram_users', 'phone_number_id')
    op.drop_column('telegram_users', 'user_name_id')
    op.add_column('user_names', sa.Column('telegram_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_names', 'user_names', ['telegram_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_names', type_='foreignkey')
    op.drop_column('user_names', 'telegram_user_id')
    op.add_column('telegram_users', sa.Column('user_name_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('telegram_users', sa.Column('phone_number_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('telegram_users', sa.Column('is_self', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'telegram_users', type_='foreignkey')
    op.drop_constraint(None, 'telegram_users', type_='foreignkey')
    op.create_foreign_key('telegram_users_phone_number_id_fkey', 'telegram_users', 'phone_numbers', ['phone_number_id'], ['id'])
    op.create_foreign_key('telegram_users_user_name_id_fkey', 'telegram_users', 'user_names', ['user_name_id'], ['id'])
    op.drop_constraint(None, 'telegram_users', type_='unique')
    op.drop_column('telegram_users', 'last_name_id')
    op.drop_column('telegram_users', 'first_name_id')
    op.drop_constraint(None, 'phone_numbers', type_='foreignkey')
    op.drop_column('phone_numbers', 'telegram_user_id')
    op.drop_table('last_names')
    op.drop_table('first_names')
    # ### end Alembic commands ###
