"""empty message

Revision ID: 6081062abf82
Revises: 0abcde47ab0f
Create Date: 2019-09-05 15:32:47.231420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6081062abf82'
down_revision = '0abcde47ab0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_names', sa.Column('username', sa.String(), nullable=False))
    op.drop_constraint('user_names_user_name_key', 'user_names', type_='unique')
    op.create_unique_constraint(None, 'user_names', ['username'])
    op.drop_column('user_names', 'user_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_names', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_names', type_='unique')
    op.create_unique_constraint('user_names_user_name_key', 'user_names', ['user_name'])
    op.drop_column('user_names', 'username')
    # ### end Alembic commands ###
